services:
  backend:
    build: ./backend/gestion.credito
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8090:8090"

  frontend:
    build: ./frontend/gestionCredito
    depends_on:
      - backend
    ports:
      - "80:80"
